# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish Release to Maven Central

permissions:
  contents: read

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

#      # 3️⃣
#      - name: Set version from release tag
#        run: |
#          env
#          echo "version=${GITHUB_REF_NAME#v}" >> gradle.properties

      # 4️⃣
      - name: Import GPG private key
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY }}" | base64 --decode > $GITHUB_WORKSPACE/secring.gpg

      # 5️⃣
      - name: Configure Gradle credentials
        run: |
          echo "mavenCentralUsername=${{ secrets.OSSRH_USERNAME }}" >> gradle.properties && \
          echo "mavenCentralPassword=${{ secrets.OSSRH_PASSWORD }}" >> gradle.properties && \
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties && \
          echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> gradle.properties && \
          echo "signing.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg" >> gradle.properties

      # 6️⃣
      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral --no-daemon
